// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying 
#define COMPAT_ATTRIBUTE attribute 
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 VARt1;
COMPAT_VARYING     vec2 _texCoord1;
COMPAT_VARYING     vec4 _position1;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
};
struct out_vertex {
    vec4 _position1;
    vec2 _texCoord1;
    vec2 VARt1;
};
out_vertex _ret_0;
input_dummy _IN1;
vec4 _r0011;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 TEX0;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    out_vertex _OUT;
    vec2 _ps;
    _r0011 = VertexCoord.x*MVPMatrix[0];
    _r0011 = _r0011 + VertexCoord.y*MVPMatrix[1];
    _r0011 = _r0011 + VertexCoord.z*MVPMatrix[2];
    _r0011 = _r0011 + VertexCoord.w*MVPMatrix[3];
    _ps = vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y);
    _OUT.VARt1 = vec2(_ps.x, _ps.y);
    _ret_0._position1 = _r0011;
    _ret_0._texCoord1 = TexCoord.xy;
    VARt1 = _OUT.VARt1;
    gl_Position = _r0011;
    TEX0.xy = TexCoord.xy;
    return;
    TEX0.xy = _ret_0._texCoord1;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec2 VARt1;
COMPAT_VARYING     vec2 _texCoord;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
};
struct out_vertex {
    vec2 _texCoord;
    vec2 VARt1;
};
vec2 _ret_0;
vec2 _TMP45;
vec2 _TMP44;
vec2 _TMP43;
vec4 _TMP42;
vec2 _TMP41;
vec2 _TMP40;
vec4 _TMP39;
vec2 _TMP38;
vec2 _TMP37;
vec4 _TMP36;
vec2 _TMP35;
vec2 _TMP34;
vec4 _TMP33;
vec2 _TMP32;
vec4 _TMP31;
vec2 _TMP30;
vec4 _TMP29;
vec2 _TMP28;
vec4 _TMP27;
vec2 _TMP26;
vec4 _TMP25;
vec2 _TMP24;
vec4 _TMP23;
vec2 _TMP22;
vec4 _TMP21;
vec2 _TMP20;
vec4 _TMP19;
vec2 _TMP18;
vec4 _TMP17;
vec2 _TMP16;
vec4 _TMP15;
vec2 _TMP14;
vec4 _TMP13;
vec2 _TMP12;
vec4 _TMP11;
vec2 _TMP10;
vec4 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec4 _TMP0;
float _TMP46;
out_vertex _VAR1;
uniform sampler2D Texture;
vec2 _c0057;
vec2 _c0061;
vec2 _c0065;
vec2 _c0069;
vec2 _c0073;
vec2 _c0077;
vec2 _c0081;
vec2 _c0085;
vec2 _c0089;
vec2 _c0095;
vec2 _c0101;
vec2 _c0107;
vec2 _c0113;
vec2 _c0119;
vec2 _c0125;
vec2 _c0131;
vec2 _c0137;
vec2 _c0143;
vec2 _c0149;
vec2 _c0155;
vec2 _c0161;
vec2 _c0167;
vec2 _c0173;
vec2 _c0179;
vec2 _x0185;
vec2 _x20185;
COMPAT_VARYING vec4 TEX0;
float _a;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    vec2 _hits;
    vec2 _L1;
    vec2 _R1;
    vec2 _U1;
    vec2 _D1;
    vec2 _L2;
    vec2 _R2;
    vec2 _U2;
    vec2 _D2;
    vec2 _UL;
    vec2 _UR;
    vec2 _DL;
    vec2 _DR;
    vec2 _ULL;
    vec2 _URR;
    vec2 _DRR;
    vec2 _DLL;
    vec2 _UUL;
    vec2 _UUR;
    vec2 _DDR;
    vec2 _DDL;
    _TMP46 = log2(1.01900000E+03);
    _a = _TMP46*6.93147182E-01;
    _TMP0 = COMPAT_TEXTURE(Texture, TEX0.xy);
    _c0057 = TEX0.xy + vec2( -1.00000000E+00, 0.00000000E+00)*VARt1;
    _TMP1 = COMPAT_TEXTURE(Texture, _c0057);
    _L1 = min(_TMP1.xy, _TMP0.xy);
    _c0061 = TEX0.xy + vec2( 1.00000000E+00, 0.00000000E+00)*VARt1;
    _TMP2 = COMPAT_TEXTURE(Texture, _c0061);
    _R1 = min(_TMP2.xy, _TMP0.xy);
    _c0065 = TEX0.xy + vec2( 0.00000000E+00, -1.00000000E+00)*VARt1;
    _TMP3 = COMPAT_TEXTURE(Texture, _c0065);
    _U1 = min(_TMP3.xy, _TMP0.xy);
    _c0069 = TEX0.xy + vec2( 0.00000000E+00, 1.00000000E+00)*VARt1;
    _TMP4 = COMPAT_TEXTURE(Texture, _c0069);
    _D1 = min(_TMP4.xy, _TMP0.xy);
    _c0073 = TEX0.xy + vec2( -2.00000000E+00, 0.00000000E+00)*VARt1;
    _TMP5 = COMPAT_TEXTURE(Texture, _c0073);
    _L2 = min(_TMP5.xy, _L1);
    _c0077 = TEX0.xy + vec2( 2.00000000E+00, 0.00000000E+00)*VARt1;
    _TMP6 = COMPAT_TEXTURE(Texture, _c0077);
    _R2 = min(_TMP6.xy, _R1);
    _c0081 = TEX0.xy + vec2( 0.00000000E+00, -2.00000000E+00)*VARt1;
    _TMP7 = COMPAT_TEXTURE(Texture, _c0081);
    _U2 = min(_TMP7.xy, _U1);
    _c0085 = TEX0.xy + vec2( 0.00000000E+00, 2.00000000E+00)*VARt1;
    _TMP8 = COMPAT_TEXTURE(Texture, _c0085);
    _D2 = min(_TMP8.xy, _D1);
    _c0089 = TEX0.xy + -VARt1;
    _TMP9 = COMPAT_TEXTURE(Texture, _c0089);
    _TMP10 = max(_L1, _U1);
    _UL = min(_TMP9.xy, _TMP10);
    _c0095 = TEX0.xy + vec2( 1.00000000E+00, -1.00000000E+00)*VARt1;
    _TMP11 = COMPAT_TEXTURE(Texture, _c0095);
    _TMP12 = max(_R1, _U1);
    _UR = min(_TMP11.xy, _TMP12);
    _c0101 = TEX0.xy + vec2( -1.00000000E+00, 1.00000000E+00)*VARt1;
    _TMP13 = COMPAT_TEXTURE(Texture, _c0101);
    _TMP14 = max(_L1, _D1);
    _DL = min(_TMP13.xy, _TMP14);
    _c0107 = TEX0.xy + VARt1;
    _TMP15 = COMPAT_TEXTURE(Texture, _c0107);
    _TMP16 = max(_R1, _D1);
    _DR = min(_TMP15.xy, _TMP16);
    _c0113 = TEX0.xy + vec2( -2.00000000E+00, -1.00000000E+00)*VARt1;
    _TMP17 = COMPAT_TEXTURE(Texture, _c0113);
    _TMP18 = max(_L2, _UL);
    _ULL = min(_TMP17.xy, _TMP18);
    _c0119 = TEX0.xy + vec2( 2.00000000E+00, -1.00000000E+00)*VARt1;
    _TMP19 = COMPAT_TEXTURE(Texture, _c0119);
    _TMP20 = max(_R2, _UR);
    _URR = min(_TMP19.xy, _TMP20);
    _c0125 = TEX0.xy + vec2( 2.00000000E+00, 1.00000000E+00)*VARt1;
    _TMP21 = COMPAT_TEXTURE(Texture, _c0125);
    _TMP22 = max(_R2, _DR);
    _DRR = min(_TMP21.xy, _TMP22);
    _c0131 = TEX0.xy + vec2( -2.00000000E+00, 1.00000000E+00)*VARt1;
    _TMP23 = COMPAT_TEXTURE(Texture, _c0131);
    _TMP24 = max(_L2, _DL);
    _DLL = min(_TMP23.xy, _TMP24);
    _c0137 = TEX0.xy + vec2( -1.00000000E+00, -2.00000000E+00)*VARt1;
    _TMP25 = COMPAT_TEXTURE(Texture, _c0137);
    _TMP26 = max(_U2, _UL);
    _UUL = min(_TMP25.xy, _TMP26);
    _c0143 = TEX0.xy + vec2( 1.00000000E+00, -2.00000000E+00)*VARt1;
    _TMP27 = COMPAT_TEXTURE(Texture, _c0143);
    _TMP28 = max(_U2, _UR);
    _UUR = min(_TMP27.xy, _TMP28);
    _c0149 = TEX0.xy + vec2( 1.00000000E+00, 2.00000000E+00)*VARt1;
    _TMP29 = COMPAT_TEXTURE(Texture, _c0149);
    _TMP30 = max(_D2, _DR);
    _DDR = min(_TMP29.xy, _TMP30);
    _c0155 = TEX0.xy + vec2( -1.00000000E+00, 2.00000000E+00)*VARt1;
    _TMP31 = COMPAT_TEXTURE(Texture, _c0155);
    _TMP32 = max(_D2, _DL);
    _DDL = min(_TMP31.xy, _TMP32);
    _c0161 = TEX0.xy + vec2( -2.00000000E+00, -2.00000000E+00)*VARt1;
    _TMP33 = COMPAT_TEXTURE(Texture, _c0161);
    _TMP34 = max(_UUL, _ULL);
    _TMP35 = min(_TMP33.xy, _TMP34);
    _c0167 = TEX0.xy + vec2( 2.00000000E+00, -2.00000000E+00)*VARt1;
    _TMP36 = COMPAT_TEXTURE(Texture, _c0167);
    _TMP37 = max(_UUR, _URR);
    _TMP38 = min(_TMP36.xy, _TMP37);
    _hits = _TMP35 + _TMP38;
    _c0173 = TEX0.xy + vec2( -2.00000000E+00, 2.00000000E+00)*VARt1;
    _TMP39 = COMPAT_TEXTURE(Texture, _c0173);
    _TMP40 = max(_DDL, _DLL);
    _TMP41 = min(_TMP39.xy, _TMP40);
    _hits = _hits + _TMP41;
    _c0179 = TEX0.xy + vec2( 2.00000000E+00, 2.00000000E+00)*VARt1;
    _TMP42 = COMPAT_TEXTURE(Texture, _c0179);
    _TMP43 = max(_DDR, _DRR);
    _TMP44 = min(_TMP42.xy, _TMP43);
    _hits = _hits + _TMP44;
    _hits = _hits + _TMP0.xy + _ULL + _URR + _DRR + _DLL + _L2 + _R2 + vec2( 0.00000000E+00, 1.00000000E+00)*(_U1 + _U2 + _D1 + _D2 + _L1 + _R1 + _UL + _UR + _DL + _DR + _UUL + _UUR + _DDR + _DDL);
    _x0185 = _a*((_hits - vec2( 3.00000000E+00, 6.00000000E+00)) + 5.00000000E-01);
    _x20185 = _x0185*_x0185;
    _TMP45 = (((_x20185 + 1.05000000E+02)*_x20185 + 9.45000000E+02)*_x0185)/(3.00000000E+01*((_x20185 + 2.80000000E+01)*_x20185 + 6.30000000E+01)) + 5.00000000E-01;
    _ret_0 = _TMP0.xy*_TMP45;
    FragColor.xy = _ret_0;
    return;
} 
#endif
