// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying 
#define COMPAT_ATTRIBUTE attribute 
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     float _frame_rotation;
COMPAT_VARYING     vec2 _tex_index;
COMPAT_VARYING     vec2 _coord_prev_prev;
COMPAT_VARYING     vec2 _coord_prev;
COMPAT_VARYING     vec2 _coord;
struct coords {
    vec2 _coord;
    vec2 _coord_prev;
    vec2 _coord_prev_prev;
    vec2 _tex_index;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
vec4 _oPosition1;
input_dummy _IN1;
vec4 _r0006;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 TEX1;
COMPAT_VARYING vec4 TEX2;
COMPAT_VARYING vec4 TEX3;
COMPAT_VARYING vec4 TEX4;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    coords _co;
    vec2 _one_x;
    _r0006 = VertexCoord.x*MVPMatrix[0];
    _r0006 = _r0006 + VertexCoord.y*MVPMatrix[1];
    _r0006 = _r0006 + VertexCoord.z*MVPMatrix[2];
    _r0006 = _r0006 + VertexCoord.w*MVPMatrix[3];
    _oPosition1 = _r0006;
    _one_x = vec2(1.00000000E+00/(3.00000000E+00*TextureSize.x), 0.00000000E+00);
    _co._coord = TexCoord.xy;
    _co._coord_prev = TexCoord.xy - _one_x;
    _co._coord_prev_prev = TexCoord.xy - 2.00000000E+00*_one_x;
    _co._tex_index = TexCoord.xy*TextureSize;
    gl_Position = _r0006;
    TEX1.xy = TexCoord.xy;
    TEX2.xy = _co._coord_prev;
    TEX3.xy = _co._coord_prev_prev;
    TEX4.xy = _co._tex_index;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     float _frame_rotation;
COMPAT_VARYING     vec2 _tex_index;
COMPAT_VARYING     vec2 _coord_prev_prev;
COMPAT_VARYING     vec2 _coord_prev;
COMPAT_VARYING     vec2 _coord;
struct coords {
    vec2 _coord;
    vec2 _coord_prev;
    vec2 _coord_prev_prev;
    vec2 _tex_index;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
vec4 _ret_0;
vec3 _TMP3;
float _TMP10;
float _TMP9;
float _TMP8;
float _TMP7;
float _TMP6;
float _TMP5;
float _TMP4;
vec4 _TMP2;
vec4 _TMP1;
vec4 _TMP0;
uniform sampler2D Texture;
float _c0014;
float _TMP21;
float _x0022;
vec3 _TMP31;
float _a0034;
float _c0034;
float _a0036;
vec3 _TMP41;
float _pixel0042;
float _a0044;
float _c0044;
float _a0046;
vec3 _TMP51;
float _pixel0052;
float _a0054;
float _c0054;
float _a0056;
COMPAT_VARYING vec4 TEX1;
COMPAT_VARYING vec4 TEX2;
COMPAT_VARYING vec4 TEX3;
COMPAT_VARYING vec4 TEX4;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    float _pixel_x;
    vec3 _result;
    vec3 _TMP12;
    _TMP4 = abs(TEX4.y);
    _TMP5 = fract(_TMP4);
    _TMP6 = abs(1.00000000E+00);
    _c0014 = _TMP5*_TMP6;
    if (TEX4.y < 0.00000000E+00) { 
        _TMP7 = -_c0014;
    } else {
        _TMP7 = _c0014;
    } 
    _x0022 = -2.00000003E-01*_TMP7;
    _TMP21 = pow(2.71828198E+00, _x0022);
    _TMP0 = COMPAT_TEXTURE(Texture, TEX1.xy);
    _TMP1 = COMPAT_TEXTURE(Texture, TEX2.xy);
    _TMP2 = COMPAT_TEXTURE(Texture, TEX3.xy);
    _pixel_x = 3.00000000E+00*TEX4.x;
    _a0034 = _pixel_x + 3.00000000E+00;
    _a0036 = _a0034/3.00000000E+00;
    _TMP4 = abs(_a0036);
    _TMP5 = fract(_TMP4);
    _TMP6 = abs(3.00000000E+00);
    _c0034 = _TMP5*_TMP6;
    if (_a0034 < 0.00000000E+00) { 
        _TMP7 = -_c0034;
    } else {
        _TMP7 = _c0034;
    } 
    if (_TMP7 >= 2.00000000E+00) { 
        _TMP31 = vec3(_TMP7 - 2.00000000E+00, 0.00000000E+00, 3.00000000E+00 - _TMP7);
    } else {
        if (_TMP7 >= 1.00000000E+00) { 
            _TMP31 = vec3(0.00000000E+00, 2.00000000E+00 - _TMP7, _TMP7 - 1.00000000E+00);
        } else {
            _TMP31 = vec3(1.00000000E+00 - _TMP7, _TMP7, 0.00000000E+00);
        } 
    } 
    _pixel0042 = _pixel_x - 1.00000000E+00;
    _a0044 = _pixel0042 + 3.00000000E+00;
    _a0046 = _a0044/3.00000000E+00;
    _TMP4 = abs(_a0046);
    _TMP5 = fract(_TMP4);
    _TMP6 = abs(3.00000000E+00);
    _c0044 = _TMP5*_TMP6;
    if (_a0044 < 0.00000000E+00) { 
        _TMP7 = -_c0044;
    } else {
        _TMP7 = _c0044;
    } 
    if (_TMP7 >= 2.00000000E+00) { 
        _TMP41 = vec3(_TMP7 - 2.00000000E+00, 0.00000000E+00, 3.00000000E+00 - _TMP7);
    } else {
        if (_TMP7 >= 1.00000000E+00) { 
            _TMP41 = vec3(0.00000000E+00, 2.00000000E+00 - _TMP7, _TMP7 - 1.00000000E+00);
        } else {
            _TMP41 = vec3(1.00000000E+00 - _TMP7, _TMP7, 0.00000000E+00);
        } 
    } 
    _pixel0052 = _pixel_x - 2.00000000E+00;
    _a0054 = _pixel0052 + 3.00000000E+00;
    _a0056 = _a0054/3.00000000E+00;
    _TMP4 = abs(_a0056);
    _TMP5 = fract(_TMP4);
    _TMP6 = abs(3.00000000E+00);
    _c0054 = _TMP5*_TMP6;
    if (_a0054 < 0.00000000E+00) { 
        _TMP7 = -_c0054;
    } else {
        _TMP7 = _c0054;
    } 
    if (_TMP7 >= 2.00000000E+00) { 
        _TMP51 = vec3(_TMP7 - 2.00000000E+00, 0.00000000E+00, 3.00000000E+00 - _TMP7);
    } else {
        if (_TMP7 >= 1.00000000E+00) { 
            _TMP51 = vec3(0.00000000E+00, 2.00000000E+00 - _TMP7, _TMP7 - 1.00000000E+00);
        } else {
            _TMP51 = vec3(1.00000000E+00 - _TMP7, _TMP7, 0.00000000E+00);
        } 
    } 
    _result = (8.00000012E-01*_TMP0.xyz)*_TMP31 + (6.00000024E-01*_TMP1.xyz)*_TMP41 + (3.00000012E-01*_TMP2.xyz)*_TMP51;
    _TMP8 = pow(_result.x, 1.39999998E+00);
    _TMP9 = pow(_result.y, 1.39999998E+00);
    _TMP10 = pow(_result.z, 1.39999998E+00);
    _TMP3 = vec3(_TMP8, _TMP9, _TMP10);
    _result = 2.29999995E+00*_TMP3;
    _TMP12 = _TMP21*_result;
    _ret_0 = vec4(_TMP12.x, _TMP12.y, _TMP12.z, 1.00000000E+00);
    FragColor = _ret_0;
    return;
} 
#endif
