// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying 
#define COMPAT_ATTRIBUTE attribute 
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t41;
COMPAT_VARYING     vec4 _t31;
COMPAT_VARYING     vec4 _t21;
COMPAT_VARYING     vec4 _t11;
COMPAT_VARYING     vec2 _CT;
COMPAT_VARYING     vec4 _position2;
COMPAT_VARYING     vec4 _color2;
COMPAT_VARYING     vec4 _t4;
COMPAT_VARYING     vec4 _t3;
COMPAT_VARYING     vec4 _t2;
COMPAT_VARYING     vec4 _t1;
COMPAT_VARYING     vec2 _texCoord1;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct VERTEX_OUTPUT {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord1;
    vec4 _t1;
    vec4 _t2;
    vec4 _t3;
    vec4 _t4;
};
struct output_dummy {
    vec4 _color2;
};
struct VERTEX_INPUT {
    vec4 _position2;
    vec2 _CT;
    vec4 _t11;
    vec4 _t21;
    vec4 _t31;
    vec4 _t41;
};
VERTEX_OUTPUT _ret_0;
input_dummy _IN1;
vec4 _r0007;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 COLOR;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 COL0;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
COMPAT_VARYING vec4 TEX2;
COMPAT_VARYING vec4 TEX3;
COMPAT_VARYING vec4 TEX4;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    VERTEX_OUTPUT _OUT;
    vec2 _ps;
    float _dx;
    float _dy;
    _r0007 = VertexCoord.x*MVPMatrix[0];
    _r0007 = _r0007 + VertexCoord.y*MVPMatrix[1];
    _r0007 = _r0007 + VertexCoord.z*MVPMatrix[2];
    _r0007 = _r0007 + VertexCoord.w*MVPMatrix[3];
    _ps = vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y);
    _dx = _ps.x*5.00000000E-01;
    _dy = _ps.y*5.00000000E-01;
    _OUT._t1.xy = TexCoord.xy + vec2(-_dx, 0.00000000E+00);
    _OUT._t2.xy = TexCoord.xy + vec2(_dx, 0.00000000E+00);
    _OUT._t3.xy = TexCoord.xy + vec2(0.00000000E+00, -_dy);
    _OUT._t4.xy = TexCoord.xy + vec2(0.00000000E+00, _dy);
    _OUT._t1.zw = TexCoord.xy + vec2(-_dx, -_dy);
    _OUT._t2.zw = TexCoord.xy + vec2(-_dx, _dy);
    _OUT._t3.zw = TexCoord.xy + vec2(_dx, -_dy);
    _OUT._t4.zw = TexCoord.xy + vec2(_dx, _dy);
    _ret_0._position1 = _r0007;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord1 = TexCoord.xy;
    _ret_0._t1 = _OUT._t1;
    _ret_0._t2 = _OUT._t2;
    _ret_0._t3 = _OUT._t3;
    _ret_0._t4 = _OUT._t4;
    gl_Position = _r0007;
    COL0 = COLOR;
    TEX0.xy = TexCoord.xy;
    TEX1 = _OUT._t1;
    TEX2 = _OUT._t2;
    TEX3 = _OUT._t3;
    TEX4 = _OUT._t4;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord1;
    TEX1 = _ret_0._t1;
    TEX2 = _ret_0._t2;
    TEX3 = _ret_0._t3;
    TEX4 = _ret_0._t4;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t4;
COMPAT_VARYING     vec4 _t3;
COMPAT_VARYING     vec4 _t21;
COMPAT_VARYING     vec4 _t11;
COMPAT_VARYING     vec2 _CT;
COMPAT_VARYING     vec4 _color1;
COMPAT_VARYING     vec4 _t41;
COMPAT_VARYING     vec4 _t31;
COMPAT_VARYING     vec4 _t22;
COMPAT_VARYING     vec4 _t12;
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     vec4 _color;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct VERTEX_OUTPUT {
    vec4 _color;
    vec2 _texCoord;
    vec4 _t12;
    vec4 _t22;
    vec4 _t31;
    vec4 _t41;
};
struct output_dummy {
    vec4 _color1;
};
struct VERTEX_INPUT {
    vec2 _CT;
    vec4 _t11;
    vec4 _t21;
    vec4 _t3;
    vec4 _t4;
};
float _TMP20;
vec3 _TMP19;
float _TMP18;
vec3 _TMP17;
float _TMP16;
vec3 _TMP15;
float _TMP22;
vec3 _TMP21;
float _TMP14;
vec3 _TMP13;
float _TMP12;
vec3 _TMP11;
float _TMP10;
vec3 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec4 _TMP0;
uniform sampler2D Texture;
vec3 _a0047;
vec3 _a0051;
vec3 _a0055;
vec3 _a0059;
vec3 _a0063;
vec3 _b0065;
vec3 _a0067;
vec3 _b0069;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
COMPAT_VARYING vec4 TEX2;
COMPAT_VARYING vec4 TEX3;
COMPAT_VARYING vec4 TEX4;
uniform vec3 _dt;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    output_dummy _OUT;
    vec3 _c00;
    vec3 _c10;
    vec3 _c20;
    vec3 _c01;
    vec3 _c11;
    vec3 _c21;
    vec3 _c02;
    vec3 _c12;
    vec3 _c22;
    float _d1;
    float _d2;
    float _hl;
    float _vl;
    float _k1;
    float _k2;
    vec3 _t1;
    vec3 _t2;
    vec3 _TMP27;
    _TMP0 = COMPAT_TEXTURE(Texture, TEX1.zw);
    _c00 = vec3(float(_TMP0.x), float(_TMP0.y), float(_TMP0.z));
    _TMP1 = COMPAT_TEXTURE(Texture, TEX3.xy);
    _c10 = vec3(float(_TMP1.x), float(_TMP1.y), float(_TMP1.z));
    _TMP2 = COMPAT_TEXTURE(Texture, TEX3.zw);
    _c20 = vec3(float(_TMP2.x), float(_TMP2.y), float(_TMP2.z));
    _TMP3 = COMPAT_TEXTURE(Texture, TEX1.xy);
    _c01 = vec3(float(_TMP3.x), float(_TMP3.y), float(_TMP3.z));
    _TMP4 = COMPAT_TEXTURE(Texture, TEX0.xy);
    _c11 = vec3(float(_TMP4.x), float(_TMP4.y), float(_TMP4.z));
    _TMP5 = COMPAT_TEXTURE(Texture, TEX2.xy);
    _c21 = vec3(float(_TMP5.x), float(_TMP5.y), float(_TMP5.z));
    _TMP6 = COMPAT_TEXTURE(Texture, TEX2.zw);
    _c02 = vec3(float(_TMP6.x), float(_TMP6.y), float(_TMP6.z));
    _TMP7 = COMPAT_TEXTURE(Texture, TEX4.xy);
    _c12 = vec3(float(_TMP7.x), float(_TMP7.y), float(_TMP7.z));
    _TMP8 = COMPAT_TEXTURE(Texture, TEX4.zw);
    _c22 = vec3(float(_TMP8.x), float(_TMP8.y), float(_TMP8.z));
    _a0047 = _c00 - _c22;
    _TMP21 = abs(vec3(float(_a0047.x), float(_a0047.y), float(_a0047.z)));
    _TMP9 = vec3(float(_TMP21.x), float(_TMP21.y), float(_TMP21.z));
    _TMP22 = dot(vec3(float(_TMP9.x), float(_TMP9.y), float(_TMP9.z)), vec3(float(_dt.x), float(_dt.y), float(_dt.z)));
    _TMP10 = float(_TMP22);
    _d1 = float((_TMP10 + 1.00016594E-04));
    _a0051 = _c20 - _c02;
    _TMP21 = abs(vec3(float(_a0051.x), float(_a0051.y), float(_a0051.z)));
    _TMP11 = vec3(float(_TMP21.x), float(_TMP21.y), float(_TMP21.z));
    _TMP22 = dot(vec3(float(_TMP11.x), float(_TMP11.y), float(_TMP11.z)), vec3(float(_dt.x), float(_dt.y), float(_dt.z)));
    _TMP12 = float(_TMP22);
    _d2 = float((_TMP12 + 1.00016594E-04));
    _a0055 = _c01 - _c21;
    _TMP21 = abs(vec3(float(_a0055.x), float(_a0055.y), float(_a0055.z)));
    _TMP13 = vec3(float(_TMP21.x), float(_TMP21.y), float(_TMP21.z));
    _TMP22 = dot(vec3(float(_TMP13.x), float(_TMP13.y), float(_TMP13.z)), vec3(float(_dt.x), float(_dt.y), float(_dt.z)));
    _TMP14 = float(_TMP22);
    _hl = float((_TMP14 + 1.00016594E-04));
    _a0059 = _c10 - _c12;
    _TMP21 = abs(vec3(float(_a0059.x), float(_a0059.y), float(_a0059.z)));
    _TMP15 = vec3(float(_TMP21.x), float(_TMP21.y), float(_TMP21.z));
    _TMP22 = dot(vec3(float(_TMP15.x), float(_TMP15.y), float(_TMP15.z)), vec3(float(_dt.x), float(_dt.y), float(_dt.z)));
    _TMP16 = float(_TMP22);
    _vl = float((_TMP16 + 1.00016594E-04));
    _k1 = 5.00000000E-01*(_hl + _vl);
    _k2 = 5.00000000E-01*(_d1 + _d2);
    _t1 = (_hl*vec3(float((_c10 + _c12).x), float((_c10 + _c12).y), float((_c10 + _c12).z)) + _vl*vec3(float((_c01 + _c21).x), float((_c01 + _c21).y), float((_c01 + _c21).z)) + _k1*vec3(float(_c11.x), float(_c11.y), float(_c11.z)))/(2.50000000E+00*(_hl + _vl));
    _t2 = (_d1*vec3(float((_c20 + _c02).x), float((_c20 + _c02).y), float((_c20 + _c02).z)) + _d2*vec3(float((_c00 + _c22).x), float((_c00 + _c22).y), float((_c00 + _c22).z)) + _k2*vec3(float(_c11.x), float(_c11.y), float(_c11.z)))/(2.50000000E+00*(_d1 + _d2));
    _a0063 = _t1 - vec3(float(_c11.x), float(_c11.y), float(_c11.z));
    _TMP17 = abs(_a0063);
    _b0065 = vec3(float(_dt.x), float(_dt.y), float(_dt.z));
    _TMP18 = dot(_TMP17, _b0065);
    _k1 = _TMP18 + 9.99999975E-05;
    _a0067 = _t2 - vec3(float(_c11.x), float(_c11.y), float(_c11.z));
    _TMP19 = abs(_a0067);
    _b0069 = vec3(float(_dt.x), float(_dt.y), float(_dt.z));
    _TMP20 = dot(_TMP19, _b0069);
    _k2 = _TMP20 + 9.99999975E-05;
    _TMP27 = (_k1*_t2 + _k2*_t1)/(_k1 + _k2);
    _OUT._color1 = vec4(_TMP27.x, _TMP27.y, _TMP27.z, 1.00000000E+00);
    FragColor = _OUT._color1;
    return;
} 
#endif
