// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)

#if __VERSION__ >= 130
#define COMPAT_VARYING out
#define COMPAT_ATTRIBUTE in
#define COMPAT_TEXTURE texture
#else
#define COMPAT_VARYING varying 
#define COMPAT_ATTRIBUTE attribute 
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t1;
COMPAT_VARYING     vec2 _texCoord1;
COMPAT_VARYING     vec4 _position1;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec4 _position1;
    vec2 _texCoord1;
    vec4 _t1;
};
out_vertex _ret_0;
input_dummy _IN1;
vec4 _r0011;
COMPAT_ATTRIBUTE vec4 VertexCoord;
COMPAT_ATTRIBUTE vec4 TexCoord;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
 
uniform mat4 MVPMatrix;
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    out_vertex _OUT;
    vec2 _ps;
    _r0011 = VertexCoord.x*MVPMatrix[0];
    _r0011 = _r0011 + VertexCoord.y*MVPMatrix[1];
    _r0011 = _r0011 + VertexCoord.z*MVPMatrix[2];
    _r0011 = _r0011 + VertexCoord.w*MVPMatrix[3];
    _ps = vec2(float((1.00000000E+00/TextureSize.x)), float((1.00000000E+00/TextureSize.y)));
    _OUT._t1.xy = vec2(0.00000000E+00, -_ps.y);
    _OUT._t1.zw = vec2(-_ps.x, 0.00000000E+00);
    _ret_0._position1 = _r0011;
    _ret_0._texCoord1 = TexCoord.xy;
    _ret_0._t1 = _OUT._t1;
    gl_Position = vec4(float(_r0011.x), float(_r0011.y), float(_r0011.z), float(_r0011.w));
    TEX0.xy = TexCoord.xy;
    TEX1 = _OUT._t1;
    return;
    TEX0.xy = _ret_0._texCoord1;
    TEX1 = _ret_0._t1;
} 
#elif defined(FRAGMENT)

#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
#define COMPAT_VARYING varying
#define FragColor gl_FragColor
#define COMPAT_TEXTURE texture2D
#endif

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#define COMPAT_PRECISION mediump
#else
#define COMPAT_PRECISION
#endif
COMPAT_VARYING     vec4 _t1;
COMPAT_VARYING     vec2 _texCoord;
COMPAT_VARYING     float _frame_rotation;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct out_vertex {
    vec2 _texCoord;
    vec4 _t1;
};
vec4 _ret_0;
vec3 _TMP29;
vec3 _TMP30;
float _TMP26;
float _TMP25;
bool _TMP24;
bool _TMP23;
bool _TMP22;
bool _TMP21;
bool _TMP20;
bool _TMP19;
bool _TMP18;
bool _TMP17;
bool _TMP16;
bool _TMP15;
bool _TMP14;
float _TMP13;
float _TMP31;
float _TMP38;
vec4 _TMP12;
vec4 _TMP11;
vec4 _TMP10;
vec4 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec2 _TMP0;
uniform sampler2D Texture;
input_dummy _IN1;
vec2 _x0046;
vec2 _val0048;
vec2 _c0050;
vec2 _c0052;
vec2 _c0054;
vec2 _c0058;
vec2 _c0060;
vec2 _c0062;
vec2 _c0064;
vec2 _c0066;
vec2 _c0068;
vec2 _c0070;
vec2 _c0072;
float _TMP125;
float _a0128;
float _TMP131;
float _a0134;
float _TMP137;
float _a0140;
float _TMP143;
float _a0146;
float _TMP149;
float _a0152;
float _TMP155;
float _a0158;
float _TMP161;
float _a0164;
float _TMP167;
float _a0170;
float _TMP173;
float _a0176;
float _TMP179;
float _a0182;
float _TMP185;
float _a0188;
float _TMP191;
float _a0194;
float _TMP195;
float _a0198;
float _TMP199;
float _a0202;
float _TMP203;
float _a0206;
float _TMP207;
float _a0210;
float _TMP213;
float _a0216;
float _TMP217;
float _a0220;
float _TMP221;
float _a0224;
float _TMP225;
float _a0228;
float _TMP229;
float _a0232;
float _TMP233;
float _a0236;
float _TMP237;
float _a0240;
COMPAT_VARYING vec4 TEX0;
COMPAT_VARYING vec4 TEX1;
 
uniform int FrameDirection;
uniform int FrameCount;
uniform COMPAT_PRECISION vec2 OutputSize;
uniform COMPAT_PRECISION vec2 TextureSize;
uniform COMPAT_PRECISION vec2 InputSize;
void main()
{
    bool _edr;
    bool _px;
    bool _interp_restriction_lv1;
    bool _nc;
    bool _fx;
    vec2 _pos;
    vec2 _dir;
    vec2 _g1;
    vec2 _g2;
    vec3 _B2;
    vec3 _C;
    vec3 _D;
    vec3 _E;
    vec3 _F;
    vec3 _G;
    vec3 _H;
    vec3 _I;
    vec3 _F4;
    vec3 _I4;
    vec3 _H5;
    vec3 _I5;
    float _b1;
    float _c1;
    float _d1;
    float _e1;
    float _f1;
    float _g3;
    float _h1;
    float _i;
    float _i4;
    float _i5;
    float _h5;
    float _f4;
    _x0046 = TEX0.xy*TextureSize;
    _TMP0 = fract(_x0046);
    _pos = _TMP0 - vec2( 5.00000000E-01, 5.00000000E-01);
    _val0048 = vec2(float((_pos.x > 0.00000000E+00)), float((_pos.y > 0.00000000E+00)));
    _dir = _val0048 - vec2(float((_pos.x < 0.00000000E+00)), float((_pos.y < 0.00000000E+00)));
    _g1 = _dir*vec2(float(TEX1.x), float(TEX1.y));
    _g2 = _dir*vec2(float(TEX1.z), float(TEX1.w));
    _c0050 = TEX0.xy + _g1;
    _TMP1 = COMPAT_TEXTURE(Texture, _c0050);
    _B2 = vec3(float(_TMP1.x), float(_TMP1.y), float(_TMP1.z));
    _c0052 = (TEX0.xy + _g1) - _g2;
    _TMP2 = COMPAT_TEXTURE(Texture, _c0052);
    _C = vec3(float(_TMP2.x), float(_TMP2.y), float(_TMP2.z));
    _c0054 = TEX0.xy + _g2;
    _TMP3 = COMPAT_TEXTURE(Texture, _c0054);
    _D = vec3(float(_TMP3.x), float(_TMP3.y), float(_TMP3.z));
    _TMP4 = COMPAT_TEXTURE(Texture, TEX0.xy);
    _E = vec3(float(_TMP4.x), float(_TMP4.y), float(_TMP4.z));
    _c0058 = TEX0.xy - _g2;
    _TMP5 = COMPAT_TEXTURE(Texture, _c0058);
    _F = vec3(float(_TMP5.x), float(_TMP5.y), float(_TMP5.z));
    _c0060 = (TEX0.xy - _g1) + _g2;
    _TMP6 = COMPAT_TEXTURE(Texture, _c0060);
    _G = vec3(float(_TMP6.x), float(_TMP6.y), float(_TMP6.z));
    _c0062 = TEX0.xy - _g1;
    _TMP7 = COMPAT_TEXTURE(Texture, _c0062);
    _H = vec3(float(_TMP7.x), float(_TMP7.y), float(_TMP7.z));
    _c0064 = (TEX0.xy - _g1) - _g2;
    _TMP8 = COMPAT_TEXTURE(Texture, _c0064);
    _I = vec3(float(_TMP8.x), float(_TMP8.y), float(_TMP8.z));
    _c0066 = TEX0.xy - 2.00000000E+00*_g2;
    _TMP9 = COMPAT_TEXTURE(Texture, _c0066);
    _F4 = vec3(float(_TMP9.x), float(_TMP9.y), float(_TMP9.z));
    _c0068 = (TEX0.xy - _g1) - 2.00000000E+00*_g2;
    _TMP10 = COMPAT_TEXTURE(Texture, _c0068);
    _I4 = vec3(float(_TMP10.x), float(_TMP10.y), float(_TMP10.z));
    _c0070 = TEX0.xy - 2.00000000E+00*_g1;
    _TMP11 = COMPAT_TEXTURE(Texture, _c0070);
    _H5 = vec3(float(_TMP11.x), float(_TMP11.y), float(_TMP11.z));
    _c0072 = (TEX0.xy - 2.00000000E+00*_g1) - _g2;
    _TMP12 = COMPAT_TEXTURE(Texture, _c0072);
    _I5 = vec3(float(_TMP12.x), float(_TMP12.y), float(_TMP12.z));
    _TMP38 = dot(vec3(float(_B2.x), float(_B2.y), float(_B2.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _b1 = float(_TMP31);
    _TMP38 = dot(vec3(float(_C.x), float(_C.y), float(_C.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _c1 = float(_TMP31);
    _TMP38 = dot(vec3(float(_D.x), float(_D.y), float(_D.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _d1 = float(_TMP31);
    _TMP38 = dot(vec3(float(_E.x), float(_E.y), float(_E.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _e1 = float(_TMP31);
    _TMP38 = dot(vec3(float(_F.x), float(_F.y), float(_F.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _f1 = float(_TMP31);
    _TMP38 = dot(vec3(float(_G.x), float(_G.y), float(_G.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _g3 = float(_TMP31);
    _TMP38 = dot(vec3(float(_H.x), float(_H.y), float(_H.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _h1 = float(_TMP31);
    _TMP38 = dot(vec3(float(_I.x), float(_I.y), float(_I.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _i = float(_TMP31);
    _TMP38 = dot(vec3(float(_I4.x), float(_I4.y), float(_I4.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _i4 = float(_TMP31);
    _TMP38 = dot(vec3(float(_I5.x), float(_I5.y), float(_I5.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _i5 = float(_TMP31);
    _TMP38 = dot(vec3(float(_H5.x), float(_H5.y), float(_H5.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _h5 = float(_TMP31);
    _TMP38 = dot(vec3(float(_F4.x), float(_F4.y), float(_F4.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _TMP31 = float(_TMP38);
    _f4 = float(_TMP31);
    _TMP13 = dot(_dir, _pos);
    _fx = _TMP13 > 5.00000000E-01;
    _a0128 = _f1 - _b1;
    _TMP125 = abs(_a0128);
    _TMP14 = _TMP125 < 1.50000000E+01;
    _a0134 = _f1 - _c1;
    _TMP131 = abs(_a0134);
    _TMP15 = _TMP131 < 1.50000000E+01;
    _a0140 = _h1 - _d1;
    _TMP137 = abs(_a0140);
    _TMP16 = _TMP137 < 1.50000000E+01;
    _a0146 = _h1 - _g3;
    _TMP143 = abs(_a0146);
    _TMP17 = _TMP143 < 1.50000000E+01;
    _a0152 = _e1 - _i;
    _TMP149 = abs(_a0152);
    _TMP18 = _TMP149 < 1.50000000E+01;
    _a0158 = _f1 - _f4;
    _TMP155 = abs(_a0158);
    _TMP19 = _TMP155 < 1.50000000E+01;
    _a0164 = _f1 - _i4;
    _TMP161 = abs(_a0164);
    _TMP20 = _TMP161 < 1.50000000E+01;
    _a0170 = _h1 - _h5;
    _TMP167 = abs(_a0170);
    _TMP21 = _TMP167 < 1.50000000E+01;
    _a0176 = _h1 - _i5;
    _TMP173 = abs(_a0176);
    _TMP22 = _TMP173 < 1.50000000E+01;
    _a0182 = _e1 - _g3;
    _TMP179 = abs(_a0182);
    _TMP23 = _TMP179 < 1.50000000E+01;
    _a0188 = _e1 - _c1;
    _TMP185 = abs(_a0188);
    _TMP24 = _TMP185 < 1.50000000E+01;
    _interp_restriction_lv1 = _e1 != _f1 && _e1 != _h1 && (!_TMP14 && !_TMP15 || !_TMP16 && !_TMP17 || _TMP18 && (!_TMP19 && !_TMP20 || !_TMP21 && !_TMP22) || _TMP23 || _TMP24);
    _a0194 = _e1 - _c1;
    _TMP191 = abs(_a0194);
    _a0198 = _e1 - _g3;
    _TMP195 = abs(_a0198);
    _a0202 = _i - _h5;
    _TMP199 = abs(_a0202);
    _a0206 = _i - _f4;
    _TMP203 = abs(_a0206);
    _a0210 = _h1 - _f1;
    _TMP207 = abs(_a0210);
    _TMP25 = _TMP191 + _TMP195 + _TMP199 + _TMP203 + 4.00000000E+00*_TMP207;
    _a0216 = _h1 - _d1;
    _TMP213 = abs(_a0216);
    _a0220 = _h1 - _i5;
    _TMP217 = abs(_a0220);
    _a0224 = _f1 - _i4;
    _TMP221 = abs(_a0224);
    _a0228 = _f1 - _b1;
    _TMP225 = abs(_a0228);
    _a0232 = _e1 - _i;
    _TMP229 = abs(_a0232);
    _TMP26 = _TMP213 + _TMP217 + _TMP221 + _TMP225 + 4.00000000E+00*_TMP229;
    _edr = _TMP25 < _TMP26 && _interp_restriction_lv1;
    _nc = _edr && _fx;
    _a0236 = _e1 - _f1;
    _TMP233 = abs(_a0236);
    _a0240 = _e1 - _h1;
    _TMP237 = abs(_a0240);
    _px = _TMP233 <= _TMP237;
    if (_nc) { 
        if (_px) { 
            _TMP30 = _F;
        } else {
            _TMP30 = _H;
        } 
        _TMP29 = _TMP30;
    } else {
        _TMP29 = _E;
    } 
    _ret_0 = vec4(_TMP29.x, _TMP29.y, _TMP29.z, 1.00000000E+00);
    FragColor = vec4(float(_ret_0.x), float(_ret_0.y), float(_ret_0.z), float(_ret_0.w));
    return;
} 
#endif
